# Laod functions
source ~/.dotfiles/shell/functions.sh

# Allow local customizations in the ~/.shell_local_before file
if [ -f ~/.shell_local_before ]; then
    source ~/.shell_local_before
fi

# Allow local customizations in the ~/.zshrc_local_before file
if [ -f ~/.zshrc_local_before ]; then
    source ~/.zshrc_local_before
fi

# External plugins (initialized before)
# For now we only have zsh-completions
source ~/.dotfiles/zsh/plugins_before.zsh

# Settings
source ~/.dotfiles/zsh/settings.zsh

# Aliases
source ~/.dotfiles/shell/aliases.sh

# Prompt
source ~/.dotfiles/zsh/prompt.zsh

# External plugins
source ~/.dotfiles/zsh/plugins_after.zsh

# Allow local customizations in the ~/.shell_local_after file
if [ -f ~/.shell_local_after ]; then
    source ~/.shell_local_after
fi

# Allow local customizations in the ~/.zshrc_local_after file
if [ -f ~/.zshrc_local_after ]; then
    source ~/.zshrc_local_after
fi

